Add language codes
bhatvikrant/world-countries-capitals pull request #59
Opened 2020-10-23 18:29 UTC by anneloreegger

Fixes #55

2020-10-23 19:12 UTC, sthiepaan requested changes
Nice job @anneloreegger! I've checked your work and it looks promising!

2020-10-23 19:12 UTC, sthiepaan commented on data/data.json
> +    "language_codes": ["ps-AF", "fa-AF"]
Can we rearrange `language_codes {Array}` elements to be sorted in alphabetical order? 
(same for lines: 19, 323, 399, 532, 570 628, 647, 1065, 1464, 1540, 1559, 1673, 1749, 1863, 1958, 1996, 2091, 2110, 2338, 2357, 2528, 2642, 2752, 2824, 2932, 3058, 3094, 3256, 3274, 3328, 3400, 3436, 3454, 3544,  3580,

2020-10-23 19:12 UTC, sthiepaan commented on data/data.json
> +    "language_codes": ["pt-PT"]},
```suggestion
    "language_codes": ["pt-PT"]
  },
```
Can we fix the formatting? (same for lines: 2680, 2698, 2716, 2734, 2752, 2770, 2788, 2806, 2824, 2842, 2860, 2878, 2896, 2914, 2932, 2950, 2968, 2986, 3004, 3022, 3040, 3058, 3076, 3094, 3112, 3130, 3148, 3166, 3202, 3220, 3238, 3256, 3274, 3292, 3310, 3328, 3346, 3364, 3382, 3400, 3418, 3436, 3454, 3472, 3490, 3508, 3526, 3544, 3562, 3580, 3598, 3616, 3634, 3652, 3670)

2020-10-23 19:14 UTC, sthiepaan commented
@anneloreegger please remember to run `npm test` to check it existing methods are still working after your changes 😉

2020-10-23 21:07 UTC, anneloreegger commented
@sthiepaan Thanks for looking at my pull request so quickly. I already implemented the requested changes, and also adapted the tests ;)

2020-10-24 07:43 UTC, sthiepaan approved these changes
LGTM 🎉

2020-10-24 12:36 UTC, merged